#!/usr/bin/env bash
# {{PREFIX}}-asset-validate.sh — deterministic asset gate for {{PROJECT_NAME}}.
# Emits exactly one JSON line on stdout. Never prints prose.
#
# Usage:
#   {{PREFIX}}-asset-validate.sh --image <path> [--tier A|B] [--profile <id|path>]
#                                [--palette <path>] [--provenance <path>]
#
# Defaults are read from art/style/style-bible.json when present, so a normal
# call is just `--image <path>`.
#
# Output (pass):
#   {"pass":true,"asset":"tower_base.png","profile":"cel-shaded-outline",...}
# Output (environment problem):
#   {"pass":false,"error_kind":"python_missing","errors":["..."]}
#
# Bash owns the contract, Python owns the pixels. An environment failure is
# reported as a distinct error_kind rather than as a failing asset — the two
# mean completely different things to whoever reads the result.

set -uo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)
IMAGE=""
TIER=""
PROFILE=""
PALETTE=""
PROVENANCE=""

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)
. "$SCRIPT_DIR/{{PREFIX}}-common.sh"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --image)      IMAGE="${2:-}"; shift 2 || shift ;;
    --tier)       TIER="${2:-}"; shift 2 || shift ;;
    --profile)    PROFILE="${2:-}"; shift 2 || shift ;;
    --palette)    PALETTE="${2:-}"; shift 2 || shift ;;
    --provenance) PROVENANCE="${2:-}"; shift 2 || shift ;;
    *) emit_error "bad_usage" "unknown argument: $1" ;;
  esac
done

[ -n "$IMAGE" ] || emit_error "bad_usage" "--image is required"
[ -f "$IMAGE" ] || emit_error "image_missing" "no such image: $IMAGE"

# ----- style bible defaults ----------------------------------------------
BIBLE="art/style/style-bible.json"
read_bible() {
  # $1 = key. Kept to a grep so the gate has no jq dependency; the style bible
  # is generated by our own agents and its shape is fixed by the schema.
  [ -f "$BIBLE" ] || return 1
  grep -o "\"$1\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$BIBLE" | head -1 |
    sed -e "s|.*:[[:space:]]*\"||" -e "s|\"$||"
}

[ -n "$PROFILE" ] || PROFILE=$(read_bible "style_profile" || true)
[ -n "$PROFILE" ] || emit_error "profile_unknown" "no --profile given and $BIBLE has no style_profile"
[ -n "$TIER" ] || TIER="B"

# A bare id resolves against the project's frozen profile copy first, then the
# pipeline's catalogue. The project copy wins on purpose: a game must keep
# building the same way after the generator moves on.
if [ ! -f "$PROFILE" ]; then
  for candidate in \
      "art/style/profiles/$PROFILE.json" \
      "$SCRIPT_DIR/../profiles/style/$PROFILE.json" \
      "$SCRIPT_DIR/profiles/style/$PROFILE.json"; do
    if [ -f "$candidate" ]; then PROFILE="$candidate"; break; fi
  done
fi
[ -f "$PROFILE" ] || emit_error "profile_unknown" "cannot resolve style profile: $PROFILE"

[ -n "$PALETTE" ] || { [ -f "art/style/palette.json" ] && PALETTE="art/style/palette.json"; }

# ----- interpreter --------------------------------------------------------
PY=""
if [ -n "${GP_PYTHON:-}" ] && "$GP_PYTHON" -c "import PIL" >/dev/null 2>&1; then
  PY="$GP_PYTHON"
else
  for c in python3 python py; do
    if command -v "$c" >/dev/null 2>&1 && "$c" -c "import PIL" >/dev/null 2>&1; then PY="$c"; break; fi
  done
fi
[ -n "$PY" ] || emit_error "python_missing" "no python interpreter with Pillow found (set GP_PYTHON or pip install Pillow)"

IMPL="$SCRIPT_DIR/{{PREFIX}}-asset-validate.py"
[ -f "$IMPL" ] || emit_error "impl_missing" "validator implementation not found at $IMPL"
IMPL=$(native_path "$IMPL")

ARGS=(--image "$IMAGE" --profile "$PROFILE" --tier "$TIER")
[ -n "$PALETTE" ] && ARGS+=(--palette "$PALETTE")
[ -n "$PROVENANCE" ] && ARGS+=(--provenance "$PROVENANCE")

OUT=$("$PY" "$IMPL" "${ARGS[@]}" 2>/dev/null)
if [ -z "$OUT" ]; then
  emit_error "validator_crashed" "the validator produced no output for $IMAGE"
fi
printf '%s\n' "$OUT"
